### ISSUE TITLE
frontend-theme-styled/../_aui_variables.scss should be generated when creating a new theme

### ISSUE THREAD

**Issue by pat270** [liferay/generator-liferay-theme#12]
We need to copy the contents of frontend-theme-styled/../_aui_variables.scss every time we make a new theme and plan on using the variables api. I think this should be done by the theme generator.

**Comment by Robert-Frampton** [comment]
Hey @pat270 

What do you think about moving the variables found in styled's _aui_variables.scss somewhere else in styled? If it adds needed functionality then it probably needs to be moved anyways, as we recommend overwriting the _aui_variables.scss file to modify Bootstrap/Lexicon variables.

**Comment by yuchi** [comment]
@pat270, why do you need to copy that file? Is it because it’s a different skeleton (from the one generated by this package) you want themes to have at the start in order to simplify the creation of a theme?

**Comment by pat270** [comment]
Hey @yuchi, If we want to leverage Sass variables in portal we're instructed to use _aui_variables.scss to overwrite them. The problem is _aui_variables.scss in styled contains paths to font-awesome. Currently, if we don't copy the path variables over to the custom theme's _aui_variables.scss we lose that reference.

@Robert-Frampton, We can do that just not sure where. I don't want to add another file to the long list of files that we already have.

**Comment by yuchi** [comment]
@pat270 Oh now I totally got it, and probably those variables should be moved away from it.

**Comment by caneta** [comment]
Don't know exactly, but... is this discussion maybe related to [this bug](https://web.liferay.com/community/forums/-/message_boards/view_message/83985729)?

**Comment by jbalsas** [comment]
Hey @pat270, is there something we still need to do about this? If so, could you please file an issue in https://github.com/liferay/liferay-themes-sdk for it so we can better track it and safely archive this repo?

Thanks!
