### ISSUE TITLE
WARN CSSselect & CSSwhat

### ISSUE THREAD

**Issue by bebjakub** [liferay/generator-liferay-theme#13]
Hello,
During installation I got this warns:

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'

thanx for your time!

**Comment by Robert-Frampton** [comment]
Hi @bebjakub 

These are just warnings that newer versions of these npm modules are available under a different name, but it won't actually affect the generator in any way. Eventually these warnings will disappear once whatever module is depending on them upgrades to the newer versions.
