### ISSUE TITLE
Generated Themes Crash Suddenly 

### ISSUE THREAD

**Issue by netlander** [liferay/generator-liferay-theme#16]
Don't mean to cross-post but this has become an issue today.

Today the generator stopped working all of a sudden, every time I try creating a theme I get the following errors in the browser and on the console:

`javax.servlet.ServletException: javax.servlet.jsp.JspException: com.liferay.portal.kernel.template.TemplateException: Unable to process template custom-theme-admin-theme_SERVLET_CONTEXT_/templates/portal_normal.ftl
	org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:905)
	org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:838)
	com.liferay.taglib.servlet.PageContextWrapper.handlePageException(PageContextWrapper.java:164)`

Further down the stack trace there's the following:

`freemarker.core._TemplateModelException: Java method Object.equals(Object) takes 1 argument, but 2 was given.
FTL stack trace (~ means nesting-related):
	- Failed at: #if stringUtil.equals(page.getType(),...  [in template custom-theme-admin-theme_SERVLET_CONTEXT_/templates/init.ftl at line 156, column 9]
	- Reached through: #include init  [in template custom-theme-admin-theme_SERVLET_CONTEXT_/templates/portal_normal.ftl at line 3, column 1]`

It seems that the problem is related to `init.ftl` at this line of code **"Object.equals(Object)" takes 1 argument, but 2 was given**

Here's the original [forum thread](https://web.liferay.com/community/forums/-/message_boards/message/86514052) posted by a colleague.

**Comment by yuchi** [comment]
You need to import the `init.ftl` file from your parent theme and fix occurences of `stringUtil.equals(x, y)` in `x == y`.

**Comment by yuchi** [comment]
This happened because they expected the `stringUtil` object to have that method, but it was added in master lately and it's not present in any GA of the portal.

**Comment by yuchi** [comment]
Also this is **not** an issue with the yeoman generator, but within the parent theme (which is also published to npm).

The problem with this generator is how it writes dependencies. A theme has `*` by default as the dependencies versions, making updating npm department a very brittle procedure.

**Comment by netlander** [comment]
Thanks. Will definitely try your suggestions but how can you explain the fact that it was working perfectly fine up till today? I haven't moved to a different version of the portal and followed the exact theme creation procedure!

**Comment by netlander** [comment]
Is the generator pulling stuff from portlal's master branch perhaps?

**Comment by yuchi** [comment]
They are publishing themes to npm from master, so yeah it «stopped working» more or less one week ago.

The issue is multi faceted:

1. The generator doesn't use a saner dependency range approach, so you get the latest available version of the parent theme («from master»)
2. There's no clear relation between the portal version and the dependencies versions which leads to these issues
3. Few recent changes were a little bit aggressive, that one is among those

**Comment by netlander** [comment]
Thanks for the clarification. makes total sense.

The remaining question is: will it be possible to correlate the generator's versions with various portal releases/branches? More importantly the GA releases.

**Comment by yuchi** [comment]
It's difficult, IMHO. Either you have a version for each GA/fixpack and you don't get updates to the theme infrastructure, or you get updates but you don't have clear relationship with portal releases.

If the portal and theme dependencies were very very «stable» (they required small changes over time) this would not be a real issue. But this is not the case, and it's not inherently bad.

In the perfect world there would be a development pipeline for every GA/fixpack release.

**Comment by yuchi** [comment]
To mitigate the issue I suggest you to fix dependencies to a working version by changing them in the _package.json_ to `^x.y.z` form.

**Comment by netlander** [comment]
Can you be a bit more specific in terms of which `^x.y.z` I need to stick with in _package.json_ if I want to stay on 7.0.2 GA3.

BTW, the fix you suggested (replacing `stringUtil.equals(x, y)` with `x == y`) worked well - thanks.

**Comment by yuchi** [comment]
You need to look at the npm dependencies versions. They have no apparent relation to the portal version.

If I have time I'll try to give you some pointers tomorrow.

**Comment by netlander** [comment]
A quick fix to a newly generated theme would be to replace `"liferay-theme-deps-7.0": "*"` with `"liferay-theme-deps-7.0": "1.0.0"`, rerun `npm install` and redeploy.

How easy is it to add a change to the generator so that it asks for a version of the portal which we want to create a theme for?

Alternatively you could hard code the version to the latest GA because I thing most developers would be interested in working on a GA release.

Giving the generator the ability to as for a GA version at creation time seems like the most elegant approach, however.

**Comment by Robert-Frampton** [comment]
Hey @netlander 

That change was actually already made in the yeoman generator. If you install the latest version it should be good to go.

And @yuchi is right, it is difficult. Going forward we're being more careful with releases of the base themes. We'll have to find some way to map portal releases with releases of the base themes. I'm open to suggestions. One idea is to use npm distribution tags when publishing those modules to npm.

In addition I would recommend using  `~x.y.z` instead of `^x.y.z`, that way you only automatically install patch releases.

**Comment by netlander** [comment]
Hey @Robert-Frampton 

Good to know that a fix was pushed to the generator. Stabilising the release cycle and using npm distribution tags might be a good solution in the long run.

In view of the fact that there are no other tooling options for generating theme osgi bundles (at least that I know of) I'd recommend keeping this issue open until a final decision is taken and a definite fix is produced.

Thanks

**Comment by jbalsas** [comment]
We've been moving all theme-related tooling to https://github.com/liferay/liferay-themes-sdk

This, in particular, is likely going to be addressed as https://github.com/liferay/liferay-themes-sdk/issues/24
