### ISSUE TITLE
"No theme found for specified theme id" after using watch 

### ISSUE THREAD

**Issue by dermoritz** [liferay/generator-liferay-theme#17]
I just tried "generator-liferay-theme". While the theme builds and deploys fine on my local "liferay-dxp-digital-enterprise-tomcat-7.0-sp3-20170503123037723" it fails to load if i use "gulp watch".

this are my developer settings (included portal-developer.properties):
`theme.css.fast.load=false
layout.template.cache.enabled=false
minifier.enabled=false`

What i did:

- gulp deploy
- set deployed theme as active -> after reload i see my changes
- gulp watch -> "Finished 'watch:setup' after" Liferay log:
`14:47:58,164 INFO  [Thread-47][BaseAutoDeployListener:42] Copying themes for C:\Users\moritz\entwicklung\svi\code\mytheme\.web_bundle_build
14:47:58,694 INFO  [Thread-47][ThemeAutoDeployer:91] Modifying themes for C:\Users\moritz\entwicklung\svi\code\mytheme\.web_bundle_build
14:47:58,970 INFO  [Thread-47][ThemeAutoDeployer:99] Themes for C:\Users\moritz\entwicklung\svi\code\mytheme\.web_bundle_build modified successfully
14:47:58,971 INFO  [Thread-47][BaseAutoDeployListener:50] Themes for C:\Users\moritz\entwicklung\svi\code\mytheme\.web_bundle_build copied successfully`
- after reload of page i get: `14:47:01,881 WARN  [http-nio-8080-exec-1][ThemeLocalServiceImpl:230] No theme found for specified theme id mytheme_WAR_mytheme. Returning the default theme.`

Is there a way to fix this?

**Comment by Robert-Frampton** [comment]
Hey @dermoritz 

Thanks for reporting, do you know what version of https://github.com/liferay/liferay-theme-tasks your theme is using? We've had reports of this issue in the past but they have since been resolved.

**Comment by dermoritz** [comment]
the generator sets liferay-theme-tasks to version * in generated package.json. this yields the current version 1.4.1.

**Comment by dermoritz** [comment]
any news here?

**Comment by Robert-Frampton** [comment]
Hey @dermoritz 

The gulp watch issues have been addressed in DXP. Your Support representative should be able to help you out regarding upgrading to the correct fix pack/service pack.

https://issues.liferay.com/browse/LPS-72409.

**Comment by dermoritz** [comment]
Thanks - we just updated to SP$ and it is working now. Feel free to close this one.

**Comment by Robert-Frampton** [comment]
Awesome, glad to hear it.

**Comment by novotny** [comment]
Hi,

I'm sorry but I'm new in Liferay portal and have the same issue with "gulp watch" and returning to the default theme.
Could someone tell me where I can download the service pack please? And write a simple manual.
But I have different liferay portal than dermoritz. 
My version si liferay-ce-portal-tomcat-7.0-ga4-20170613175008905

Thanks for your help

**Comment by yuchi** [comment]
Unfortunately service packs (and fix packs) are for the DXP product — formerly known as Liferay Portal EE (Enterprise Edition).

Later in this month Liferay.com portal CE GA5 should be released, and should contain the fixes for this problem too. (Actually didn't check the commits, but its way probable)

**Comment by novotny** [comment]
@yuchi Ok. Thanks for the info

**Comment by WHI-CH** [comment]
Still having the same issue from time to time in GA6

**Comment by Coty-OPI** [comment]
Im having the same issue on GA7
