### ISSUE TITLE
Bus error: 10 on build:compile-lib-sass

### ISSUE THREAD

**Issue by maartenvh** [liferay/generator-liferay-theme#19]
Hi

I'm creating themes and for Liferay DXP it always went well. But now I keep getting this error and the gulp process stops.
error:
```
Nognix-MBP:lf-7-test-theme mvanheiningen$ gulp build:compile-lib-sass
[10:48:15] Using gulpfile ~/Workshop/Themes/lf-7-test-theme/gulpfile.js
[10:48:15] Starting 'build:compile-lib-sass'...
Bus error: 10
Nognix-MBP:lf-7-test-theme mvanheiningen$
```
Is there something wrong? I have tried to update all npm modules but it still throws this error.

Best regards,
Maarten

**Comment by yuchi** [comment]
Version of node and npm?

This is usually thrown when _libsass_ has been built for a different version of node.

**Comment by maartenvh** [comment]
Hi Pier Paolo,

My Node is at version 5.1.0 and NPM is at version 4.0.5

Best regards,
Maarten

**Comment by yuchi** [comment]
You should, first of all, upgrade to a stable Node version. (Odd major are “unstable” and event major are “stable”, so v6 would be good).

Then you need to remove _./node_modules_ from the theme and re-install them with `npm install`.

You could actually just rebuild them but it’s cleaner to just throw them all and re install them.
Please pay attention: we are not talking about global modules installed with `npm install --global` but the local dependencies of your theme.

**Comment by maartenvh** [comment]
Hi Pier Paolo,

This fixed it I  ran ncu -g which gave me a lt of updates as well. So now all are up to date and the build process is running again like it should.

Thanks for helping :)) See you at the DevCon in Amsterdam?

Best regards
Maarten

**Comment by yuchi** [comment]
> Thanks for helping :))

Glad to! Please also close the issue since it was solved!

> See you at the DevCon in Amsterdam?

Hopefully yes :)

**Comment by jbalsas** [comment]
Thanks a lot, guys!! (@yuchi always to the rescue!! 😍 )
