### ISSUE TITLE
7.1 Theme Template

### ISSUE THREAD

**Issue by robframpton** [liferay/generator-liferay-theme#23]
A `7.1` option needs to be added to the generator in prep for Portal 7.1 that generates a 7.1 compliant theme.

**Comment by blzaugg** [comment]
Just curious; how much does a 7.0 & 7.1 theme differ?

**Comment by Robert-Frampton** [comment]
Mostly file name changes, since 7.1 will have Clay, and we've dropped the `aui` folder that those files used to be included in.

But since 7.1 is still in development, there are changes yet to come. So we don't fully know at this point.

**Comment by sbaechler** [comment]
@jbalsas Why is this issue closed? There is still no 7.1 template. The main template is different from the 7.0 template.

**Comment by jbalsas** [comment]
Hey @sbaechler, this repo is being moved to [https://github.com/liferay/liferay-themes-sdk/tree/master/packages/generator-liferay-theme](liferay-themes-sdk) together with all the related theme tooling for a simpler management.

The released versions of the generator (currently 8.0.0-beta.1) support generating themes for 7.1.

Please, feel free to file any issues in the [liferay-themes-sdk repo](https://github.com/liferay/liferay-themes-sdk/issues/new) if you still find problems with this.

Thanks!
