### ISSUE TITLE
Improve version specific dependency handling

### ISSUE THREAD

**Issue by robframpton** [liferay/generator-liferay-theme#24]
Currently we have some "presets" for dependencies that are specific to versions of Portal.

https://www.npmjs.com/package/liferay-theme-deps-7.0
https://www.npmjs.com/package/liferay-theme-deps-6.2

What we've seen is this hides too much information from theme developers, they want to know which versions of the base themes they are using (because some versions of those base themes are not compatible with certain fixpacks).

We need to provide a better way for notifying the theme developer which base themes they should be using depending on their version of DXP.

**Comment by jbalsas** [comment]
See https://github.com/liferay/liferay-themes-sdk/issues/24
