### ISSUE TITLE
Remove publishConfig property from package.json

### ISSUE THREAD

**Issue by alexandervalencia** [liferay/generator-liferay-theme#25]
In order to avoid confusion and unnecessary code, we should remove the publishConfig property from package.json.

**Comment by jbalsas** [comment]
Hey @alexandervalencia, this was merged and I've just released it as `generator-liferay-theme@7.2.0`.

This now leaves in https://github.com/liferay/liferay-themes-sdk/tree/master/packages/generator-liferay-theme, I'll be archiving this repo soon!
