### ISSUE TITLE
Generator does not use the latest liferay-theme-deps-7.0

### ISSUE THREAD

**Issue by balcsida** [liferay/generator-liferay-theme#28]
It causes error while npm install as 1.0.0 uses very old version (2.1.1) from gulp-sass which depends on node-sass@3.13.1
node-sass install.js has to download binary files from it's github repo (eg. https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-57_binding.node) which is not available thus fails.

https://github.com/Robert-Frampton/liferay-theme-deps-7.0/compare/v1.1.0...master

**Comment by balcsida** [comment]
Additionally, I understand that I used node 8.7.0 which is not recommended, but the node-sass lacks support for current latest LTS release (6.11.4 LTS), too

```
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-48_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-48_binding.node":

ESOCKETTIMEDOUT

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
```

**Comment by Robert-Frampton** [comment]
33edd02326c8370eb8d08633475eb05b1df1042d
