### ISSUE TITLE
The generated theme should have a liferay-look-and-feel.xml

### ISSUE THREAD

**Issue by natecavanaugh** [liferay/generator-liferay-theme#3]
Currently, the generated theme does not include liferay-look-and-feel.xml. We should definitely create one in the template so we can allow people to specify different theme settings.

Also, one other option might be to instead, create it in the src as a json, and during build, we convert it over to being an xml file (as this would make modifying the specific theme settings a bit easier to write and read), but it's not mandatory.

**Comment by Robert-Frampton** [comment]
See 85ae235a8ddb5b275ed7f7ed63a3e81bc8484cae
