### ISSUE TITLE
Transfer analytics account permissions

### ISSUE THREAD

**Issue by jbalsas** [liferay/generator-liferay-theme#30]
We are currently tracking usage metrics through a particular [trackingCode](https://github.com/liferay/generator-liferay-theme/blob/master/generators/app/index.js#L19).

@robframpton, I think you added @izaera to the analytics account, but I'm not sure if he got admin permissions. Could you either promote him or add @zenorocha too so he can manage it and move it with the rest of our tracked apps?

Thanks!

**Comment by robframpton** [comment]
Unfortunately that account was tied to me work email, which is suspended now :(

Not sure if there is a way to recover it.

**Comment by jbalsas** [comment]
No worries, I'm sure there's something we can do. I can check with @izaera tomorrow.

In the meantime, @jeffreydothan, do you have access to Rob's old account? Can you help @zenorocha recover the associated analytics account so we can set up the proper permissions?

**Comment by jbalsas** [comment]
This is done, @izaera had access :)
