### ISSUE TITLE
Replace the README in this repo with a link to the new repo

### ISSUE THREAD

**Issue by sbaechler** [liferay/generator-liferay-theme#32]
The new location is: https://github.com/liferay/liferay-themes-sdk

You can create a new branch with the link and set this as the default for this repo.

**Comment by lucastheisen** [comment]
Does this mean `liferay-themes-sdk` is going to replace the theme generator?  Will it only be for Liferay 8?

**Comment by sbaechler** [comment]
@lucastheisen They just switched the code over to a Monorepo.

Everything is still there: https://github.com/liferay/liferay-themes-sdk/tree/master/packages/generator-liferay-theme
