### ISSUE TITLE
Cannot find module 'unicode/category/So'

### ISSUE THREAD

**Issue by caneta** [liferay/generator-liferay-theme#8]
I've tryied to run it but i get the following.
```
user@host:yo-liferay$ yo liferay-theme
module.js:338
    throw err;
          ^
Error: Cannot find module 'unicode/category/So'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at symbols (/home/user/.nvm/versions/node/v0.12.7/lib/node_modules/generator-liferay-theme/node_modules/slug/slug.js:6:16)
    at /home/user/.nvm/versions/node/v0.12.7/lib/node_modules/generator-liferay-theme/node_modules/slug/slug.js:169:5
    at Object.<anonymous> (/home/user/.nvm/versions/node/v0.12.7/lib/node_modules/generator-liferay-theme/node_modules/slug/slug.js:179:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```
I'm using node 0.12.7 on Ubuntu 64 bit...what am I missing?

**Comment by yuchi** [comment]
The maintainer of the `slug` package on npm choose to support [only Node `≥ 0.4.x`](https://github.com/dodo/node-slug/blob/85ded30a95760b19cd223abe668eade0279a21f2/package.json#L8). That’s probably what gets in the middle.

**Comment by caneta** [comment]
But, as reported above, I used node 0.12.7 which is ≥ 0.4.x ([node release history](https://nodejs.org/en/download/releases/))

**Comment by yuchi** [comment]
Sorry, I missread it as `4.x`! The unicode package has an installation procedure, could that one have failed?

**Comment by caneta** [comment]
Of which procedure are you talking about?
I've only used the informations reported in the generator-liferay-theme [README.md](https://github.com/liferay/generator-liferay-theme/blob/master/README.md) file:
```
npm install -g yo gulp
yo liferay-theme
```
and then got the error.
No previous setup of Unicode or something else are reported here...

**Comment by caneta** [comment]
I've cleaned up my environment from previous installation and restarted from scratch: in this way I was able to create a liferay theme scaffold without errors.
By the way, I've used the latest node and npm versions: node-5.1.0 and npm-3.5.1.
Thanks for your support!

**Comment by yuchi** [comment]
It is a common issue with packages that have an installation phase.
Glad I helped you, @caneta. Could you close this issue now?

**Comment by caneta** [comment]
Sure.

**Comment by natecavanaugh** [comment]
Thanks @yuchi for helping @caneta out :) I missed the notification for this one.
