### ISSUE TITLE
What about maven?

### ISSUE THREAD

**Issue by deadcyclo** [liferay/generator-liferay-theme#9]
Would it be possible to have an option for importing themes created using maven, not only sdk-themes?

**Comment by yuchi** [comment]
I *believe* there’s not a lot you should do. Just create a new theme and import the `src/main/webapp` as `src`.

**Comment by crisp2u** [comment]
@yuchi Can you elaborate a bit ? I'm having problems building this with maven because of the different file structure

**Comment by yuchi** [comment]
If you are having issue in «building **through maven** a theme built with this new structure» it's a completely different story. I thought you was migrating from maven to gulp+npm.

If you still want to use maven I don't know if there are archetypes for the new theme structure. I'll let Robert answer this.

If you want to migrate from maven to gulp+npm then what you need to do (if you were correctly using the archetypes) is to generate a new theme and bring the files you had under *src/main/webapp* in the *src* folder in the root of the newly generated theme. As far as I know you won't be able to build/compile/deploy it using maven anymore, currently.

**Comment by yuchi** [comment]
(Sorry for typos)

**Comment by crisp2u** [comment]
Well, it actually goes like this. We rewrote one of our themes for 6.2 and decided to use the new theme generator and sdk. Now I need to integrate this into our build and deploy pipeline and I can either try to mavenize this or change my build process and add gulp in it

**Comment by yuchi** [comment]
My suggestion is to not use maven and let npm be available in your CI.

To build a theme from scratch simply run `npm install` from the root of the theme and then you'll be able to execute the build tasks as `node_modules/.bin/gulp <TASK>`.

You can run `npm install` again, without any noticeable side effects.

Just make sure in the CI there's Node.js installed, both `node` and `npm` are in the path, and that the server sees the internet and the npm registry.

**Comment by Robert-Frampton** [comment]
Hey @crisp2u 

I agree with @yuchi, if you are using these tools for theme development I'd recommend just using npm/gulp for deployment.

If there is something you think we could add to these tools to make maven integration easier, please feel free to open another issue.
